#!/usr/bin/env bash
### seth-ls -- display a list of your local accounts and balances
set -e
accounts=$(seth accounts | awk '{print $1}')
price=$2
total=0
erc20=$1
for x in $accounts; do
  balance=$(seth erc20balance $erc20 $x)
  total=$(bc <<< "$total + $balance");
  printf "%s\t%s\t%s\t%s\n" "$x" "$balance"  "$""$(bc <<< "scale=2;$price * $balance / 1")"
done
printf "\n%s\t%s\t%s\t%s\n" "Total:" "$total"  "$""$(bc <<< "scale=2;$price * $total / 1")"